# Use the official OpenJDK image as the base image
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file generated by your Spring Boot application into the container
COPY target/course-management.jar .

# Expose the port your Spring Boot application is listening on (change 8080 to your application's port if needed)
EXPOSE 8080

# Define the default command to run your Spring Boot application
CMD ["java", "-jar", "course-management.jar"]
